package information.enemy.enemyopeners;

public enum EnemyStrategyName {
    FOURPOOL, NINEPOOL, NINEPOOLSPEEDLING, CANNONRUSH, GASSTEAL, CCFIRST, FOURRAX,
    TWOFACTANK, BUNKERRUSH, SCVRUSH, ONEBASEMUTA, ONEBASELURKER,
    THREEHATCHBEFOREPOOL, TWOBASELURKER, DTRUSH, FFE, TWOGATE,
    NEXUSFIRST, DRAGOONRANGERUSH, SHUTTLERUSH, DOUBLEEIGHTRAX, TWOBASEMUTA
}
